package game

import . "github.com/ajdnik/gozork/engine"

var (
	buzzWords = []string{
		"again", "g", "oops", "a", "an", "the",
		"is", "and", "of", "then", "all", "one",
		"but", "except", ".", ",", "\"", "yes",
		"no", "y", "here",
	}
	synonyms = map[string]string{
		"using":      "with",
		"through":    "with",
		"thru":       "with",
		"into":       "in",
		"inside":     "in",
		"onto":       "on",
		"underneath": "under",
		"beneath":    "under",
		"below":      "under",
		"n":          "north",
		"s":          "south",
		"e":          "east",
		"w":          "west",
		"d":          "down",
		"u":          "up",
		"nw":         "northwest",
		"ne":         "northeast",
		"sw":         "southwest",
		"se":         "southeast",
		"superbrief": "super",
		"i":          "inventory",
		"q":          "quit",
		"l":          "look",
		"stare":      "look",
		"gaze":       "look",
		"describe":   "examine",
		"what":       "examine",
		"whats":      "examine",
		"go":         "walk",
		"run":        "walk",
		"step":       "walk",
		"proceed":    "walk",
		"xyzzy":      "plugh",
		"awake":      "wake",
		"surprise":   "wake",
		"startle":    "wake",
		"reply":      "answer",
		"fight":      "attack",
		"hurt":       "attack",
		"injure":     "attack",
		"hit":        "attack",
		"murder":     "kill",
		"slay":       "kill",
		"dispatch":   "kill",
		"rap":        "knock",
		"clean":      "brush",
		"sit":        "climb",
		"get":        "take",
		"hold":       "take",
		"carry":      "take",
		"remove":     "take",
		"grab":       "take",
		"catch":      "take",
		"incinerate": "burn",
		"ignite":     "burn",
		"lose":       "chomp",
		"barf":       "chomp",
		"ford":       "cross",
		"slice":      "cut",
		"pierce":     "cut",
		"shit":       "curse",
		"fuck":       "curse",
		"damn":       "curse",
		"damage":     "destroy",
		"break":      "destroy",
		"block":      "destroy",
		"smash":      "destroy",
		"imbibe":     "drink",
		"swallow":    "drink",
		"consume":    "eat",
		"taste":      "eat",
		"bite":       "eat",
		"banish":     "exorcise",
		"cast":       "exorcise",
		"drive":      "exorcise",
		"begone":     "exorcise",
		"douse":      "extinguish",
		"where":      "find",
		"seek":       "find",
		"see":        "find",
		"pursue":     "follow",
		"chase":      "follow",
		"come":       "follow",
		"donate":     "give",
		"offer":      "give",
		"feed":       "give",
		"hi":         "hello",
		"chant":      "incant",
		"leap":       "jump",
		"dive":       "jump",
		"taunt":      "kick",
		"oil":        "lubricate",
		"grease":     "lubricate",
		"liquify":    "melt",
		"sigh":       "mumble",
		"ulysses":    "odysseus",
		"glue":       "plug",
		"patch":      "plug",
		"repair":     "plug",
		"fix":        "plug",
		"spill":      "pour",
		"tug":        "pull",
		"yank":       "pull",
		"press":      "push",
		"stuff":      "put",
		"insert":     "put",
		"place":      "put",
		"hide":       "put",
		"lift":       "raise",
		"molest":     "rape",
		"skim":       "read",
		"peal":       "ring",
		"touch":      "rub",
		"feel":       "rub",
		"pat":        "rub",
		"pet":        "rub",
		"hop":        "skip",
		"sniff":      "smell",
		"bathe":      "swim",
		"wade":       "swim",
		"thrust":     "swing",
		"ask":        "tell",
		"hurl":       "throw",
		"chuck":      "throw",
		"toss":       "throw",
		"fasten":     "tie",
		"secure":     "tie",
		"attach":     "tie",
		"temple":     "treasure",
		"set":        "turn",
		"flip":       "turn",
		"shut":       "turn",
		"free":       "untie",
		"release":    "untie",
		"unfasten":   "untie",
		"unattach":   "untie",
		"unhook":     "untie",
		"z":          "wait",
		"brandish":   "wave",
		"winnage":    "win",
		"scream":     "yell",
		"shout":      "yell",
	}
	gameCommands = []Syntx{
		{
			Verb:   "verbose",
			Action: vVerbose,
		},
		{
			Verb:   "brief",
			Action: vBrief,
		},
		{
			Verb:   "super",
			Action: vSuperBrief,
		},
		{
			Verb:   "inventory",
			Action: vInventory,
		},
		{
			Verb:   "quit",
			Action: vQuit,
		},
		{
			Verb:   "restart",
			Action: vRestart,
		},
		{
			Verb:   "restore",
			Action: vRestore,
		},
		{
			Verb:   "save",
			Action: vSave,
		},
		{
			Verb:   "score",
			Action: vScore,
		},
		{
			Verb:   "diagnose",
			Action: vDiagnose,
		},
		{
			Verb:   "script",
			Action: vScript,
		},
		{
			Verb:   "unscript",
			Action: vUnscript,
		},
		{
			Verb:   "version",
			Action: vVersion,
		},
		{
			Verb:   "verify",
			Action: vVerify,
		},
		{
			Verb:   "answer",
			Action: vAnswer,
		},
		{
			Verb:     "activate",
			Obj1:     ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgLight, LocFlags: LocFlags{LocHeld, LocCarried, LocOnGrnd, LocInRoom}},
			Action:   vLampOn,
			NormVerb: "lamp on",
		},
		{
			Verb:   "answer",
			Action: vAnswer,
		},
		{
			Verb:     "answer",
			Obj1:     ObjProp{HasObj: true},
			Action:   vReply,
			NormVerb: "reply",
		},
		{
			Verb:    "attack",
			Obj1:    ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgPerson, LocFlags: LocFlags{LocInRoom, LocOnGrnd}},
			ObjPrep: "with",
			Obj2:    ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgWeapon, LocFlags: LocFlags{LocHeld, LocCarried, LocHave}},
			Action:  vAttack,
		},
		{
			Verb:   "back",
			Action: vBack,
		},
		{
			Verb:   "blast",
			Action: vBlast,
		},
		{
			Verb:     "blow",
			VrbPrep:  "out",
			Obj1:     ObjProp{HasObj: true},
			Action:   vLampOff,
			NormVerb: "lamp off",
		},
		{
			Verb:     "blow",
			VrbPrep:  "up",
			Obj1:     ObjProp{HasObj: true},
			Action:   vBlast,
			NormVerb: "blast",
		},
		{
			Verb:     "blow",
			VrbPrep:  "in",
			Obj1:     ObjProp{HasObj: true},
			Action:   vBreathe,
			NormVerb: "breathe",
		},
		{
			Verb:     "blow",
			VrbPrep:  "up",
			Obj1:     ObjProp{HasObj: true},
			ObjPrep:  "with",
			Obj2:     ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgTool, LocFlags: LocFlags{LocOnGrnd, LocInRoom, LocHeld, LocCarried}},
			Action:   vInflate,
			NormVerb: "inflate",
		},
		{
			Verb:      "board",
			Obj1:      ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgVeh, LocFlags: LocFlags{LocOnGrnd, LocInRoom}},
			Action:    vBoard,
			PreAction: preBoard,
		},
		{
			Verb:   "brush",
			Obj1:   ObjProp{HasObj: true, LocFlags: LocFlags{LocOnGrnd, LocInRoom, LocCarried, LocHeld}},
			Action: vBrush,
		},
		{
			Verb:    "brush",
			Obj1:    ObjProp{HasObj: true, LocFlags: LocFlags{LocOnGrnd, LocInRoom, LocCarried, LocHeld}},
			ObjPrep: "with",
			Obj2:    ObjProp{HasObj: true},
			Action:  vBrush,
		},
		{
			Verb:   "bug",
			Action: vBug,
		},
		{
			Verb:      "burn",
			Obj1:      ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgBurn, LocFlags: LocFlags{LocInRoom, LocOnGrnd, LocHeld, LocCarried}},
			ObjPrep:   "with",
			Obj2:      ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgFlame, LocFlags: LocFlags{LocHeld, LocCarried, LocHave, LocInRoom, LocOnGrnd}},
			Action:    vBurn,
			PreAction: preBurn,
		},
		{
			Verb:      "burn",
			VrbPrep:   "down",
			Obj1:      ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgBurn, LocFlags: LocFlags{LocInRoom, LocOnGrnd, LocHeld, LocCarried}},
			ObjPrep:   "with",
			Obj2:      ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgFlame, LocFlags: LocFlags{LocHeld, LocCarried, LocHave, LocInRoom, LocOnGrnd}},
			Action:    vBurn,
			PreAction: preBurn,
			NormVerb:  "burn",
		},
		{
			Verb:   "chomp",
			Action: vChomp,
		},
		{
			Verb:    "climb",
			VrbPrep: "up",
			Obj1:    ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgKludge},
			Action:  vClimbUp,
		},
		{
			Verb:    "climb",
			VrbPrep: "up",
			Obj1:    ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgClimb, LocFlags: LocFlags{LocOnGrnd, LocInRoom}},
			Action:  vClimbUp,
		},
		{
			Verb:    "climb",
			VrbPrep: "down",
			Obj1:    ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgKludge},
			Action:  vClimbDown,
		},
		{
			Verb:    "climb",
			VrbPrep: "down",
			Obj1:    ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgClimb, LocFlags: LocFlags{LocOnGrnd, LocInRoom}},
			Action:  vClimbDown,
		},
		{
			Verb:     "climb",
			Obj1:     ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgClimb, LocFlags: LocFlags{LocOnGrnd, LocInRoom}},
			Action:   vClimbFoo,
			NormVerb: "climb foo",
		},
		{
			Verb:      "climb",
			VrbPrep:   "in",
			Obj1:      ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgVeh, LocFlags: LocFlags{LocOnGrnd, LocInRoom}},
			Action:    vBoard,
			PreAction: preBoard,
			NormVerb:  "board",
		},
		{
			Verb:    "climb",
			VrbPrep: "on",
			Obj1:    ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgVeh, LocFlags: LocFlags{LocOnGrnd, LocInRoom}},
			Action:  vClimbOn,
		},
		{
			Verb:     "climb",
			VrbPrep:  "with",
			Obj1:     ObjProp{HasObj: true},
			Action:   vThrough,
			NormVerb: "through",
		},
		{
			Verb:   "close",
			Obj1:   ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgDoor, LocFlags: LocFlags{LocOnGrnd, LocInRoom, LocHeld, LocCarried}},
			Action: vClose,
		},
		{
			Verb:   "command",
			Obj1:   ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgPerson},
			Action: vCommand,
		},
		{
			Verb:   "count",
			Obj1:   ObjProp{HasObj: true},
			Action: vCount,
		},
		{
			Verb:   "cross",
			Obj1:   ObjProp{HasObj: true},
			Action: vCross,
		},
		{
			Verb:   "curse",
			Action: vCurses,
		},
		{
			Verb:   "curse",
			Obj1:   ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgPerson},
			Action: vCurses,
		},
		{
			Verb:    "cut",
			Obj1:    ObjProp{HasObj: true},
			ObjPrep: "with",
			Obj2:    ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgWeapon, LocFlags: LocFlags{LocHeld, LocCarried}},
			Action:  vCut,
		},
		{
			Verb:   "deflate",
			Obj1:   ObjProp{HasObj: true},
			Action: vDeflate,
		},
		{
			Verb:      "destroy",
			Obj1:      ObjProp{HasObj: true, LocFlags: LocFlags{LocOnGrnd, LocInRoom, LocHeld, LocCarried}},
			ObjPrep:   "with",
			Obj2:      ObjProp{HasObj: true, LocFlags: LocFlags{LocHeld, LocCarried, LocTake}},
			Action:    vMung,
			PreAction: preMung,
			NormVerb:  "mung",
		},
		{
			Verb:      "destroy",
			VrbPrep:   "down",
			Obj1:      ObjProp{HasObj: true, LocFlags: LocFlags{LocOnGrnd, LocInRoom, LocHeld, LocCarried}},
			ObjPrep:   "with",
			Obj2:      ObjProp{HasObj: true, LocFlags: LocFlags{LocHeld, LocCarried, LocTake}},
			Action:    vMung,
			PreAction: preMung,
			NormVerb:  "mung",
		},
		{
			Verb:     "destroy",
			VrbPrep:  "in",
			Obj1:     ObjProp{HasObj: true, LocFlags: LocFlags{LocOnGrnd, LocInRoom, LocHeld, LocCarried}},
			Action:   vOpen,
			NormVerb: "open",
		},
		{
			Verb:     "dig",
			VrbPrep:  "in",
			Obj1:     ObjProp{HasObj: true, LocFlags: LocFlags{LocOnGrnd, LocInRoom}},
			Action:   vDig,
			NormVerb: "dig",
		},
		{
			Verb:     "dig",
			VrbPrep:  "in",
			Obj1:     ObjProp{HasObj: true, LocFlags: LocFlags{LocInRoom, LocOnGrnd}},
			ObjPrep:  "with",
			Obj2:     ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgTool, LocFlags: LocFlags{LocHeld, LocCarried, LocHave}},
			Action:   vDig,
			NormVerb: "dig",
		},
		{
			Verb:    "dig",
			Obj1:    ObjProp{HasObj: true, LocFlags: LocFlags{LocInRoom, LocOnGrnd}},
			ObjPrep: "with",
			Obj2:    ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgTool, LocFlags: LocFlags{LocHeld, LocCarried, LocHave}},
			Action:  vDig,
		},
		{
			Verb:   "disembark",
			Obj1:   ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgVeh, LocFlags: LocFlags{LocOnGrnd, LocInRoom}},
			Action: vDisembark,
		},
		{
			Verb:   "disenchant",
			Obj1:   ObjProp{HasObj: true},
			Action: vDisenchant,
		},
		{
			Verb:   "drink",
			Obj1:   ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgDrink, LocFlags: LocFlags{LocHeld, LocCarried, LocOnGrnd, LocInRoom}},
			Action: vDrink,
		},
		{
			Verb:    "drink",
			VrbPrep: "from",
			Obj1:    ObjProp{HasObj: true, LocFlags: LocFlags{LocHeld, LocCarried}},
			Action:  vDrinkFrom,
		},
		{
			Verb:      "drop",
			Obj1:      ObjProp{HasObj: true, LocFlags: LocFlags{LocHeld, LocHave, LocMany}},
			Action:    vDrop,
			PreAction: preDrop,
		},
		{
			Verb:      "drop",
			Obj1:      ObjProp{HasObj: true, LocFlags: LocFlags{LocHeld, LocHave, LocMany}},
			ObjPrep:   "down",
			Obj2:      ObjProp{HasObj: true},
			Action:    vPut,
			PreAction: prePut,
			NormVerb:  "put",
		},
		{
			Verb:      "drop",
			Obj1:      ObjProp{HasObj: true, LocFlags: LocFlags{LocHeld, LocHave, LocMany}},
			ObjPrep:   "in",
			Obj2:      ObjProp{HasObj: true},
			Action:    vPut,
			PreAction: prePut,
			NormVerb:  "put",
		},
		{
			Verb:      "drop",
			Obj1:      ObjProp{HasObj: true, LocFlags: LocFlags{LocHeld, LocHave, LocMany}},
			ObjPrep:   "on",
			Obj2:      ObjProp{HasObj: true},
			Action:    vPutOn,
			PreAction: prePut,
			NormVerb:  "put on",
		},
		{
			Verb:      "eat",
			Obj1:      ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgFood, LocFlags: LocFlags{LocHeld, LocCarried, LocOnGrnd, LocInRoom, LocTake}},
			Action:    vDrop,
			PreAction: preDrop,
		},
		{
			Verb:   "echo",
			Action: vEcho,
		},
		{
			Verb:   "enchant",
			Obj1:   ObjProp{HasObj: true, LocFlags: LocFlags{LocOnGrnd, LocInRoom}},
			Action: vEnchant,
		},
		{
			Verb:   "enter",
			Action: vEnter,
		},
		{
			Verb:     "enter",
			Obj1:     ObjProp{HasObj: true},
			Action:   vThrough,
			NormVerb: "through",
		},
		{
			Verb:   "exit",
			Action: vExit,
		},
		{
			Verb:   "exit",
			Obj1:   ObjProp{HasObj: true},
			Action: vExit,
		},
		{
			Verb:   "examine",
			Obj1:   ObjProp{HasObj: true, LocFlags: LocFlags{LocMany}},
			Action: vExamine,
		},
		{
			Verb:     "examine",
			VrbPrep:  "in",
			Obj1:     ObjProp{HasObj: true, LocFlags: LocFlags{LocHeld, LocCarried, LocInRoom, LocOnGrnd, LocMany}},
			Action:   vLookInside,
			NormVerb: "look inside",
		},
		{
			Verb:     "examine",
			VrbPrep:  "on",
			Obj1:     ObjProp{HasObj: true, LocFlags: LocFlags{LocHeld, LocCarried, LocInRoom, LocOnGrnd, LocMany}},
			Action:   vLookInside,
			NormVerb: "look inside",
		},
		{
			Verb:   "exorcise",
			Obj1:   ObjProp{HasObj: true},
			Action: vExcorcise,
		},
		{
			Verb:     "exorcise",
			VrbPrep:  "out",
			Obj1:     ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgPerson},
			Action:   vExcorcise,
			NormVerb: "exorcise",
		},
		{
			Verb:     "exorcise",
			VrbPrep:  "away",
			Obj1:     ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgPerson},
			Action:   vExcorcise,
			NormVerb: "exorcise",
		},
		{
			Verb:     "extinguish",
			Obj1:     ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgOn, LocFlags: LocFlags{LocHeld, LocCarried, LocOnGrnd, LocInRoom, LocTake, LocHave}},
			Action:   vLampOff,
			NormVerb: "lamp off",
		},
		{
			Verb:      "fill",
			Obj1:      ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgCont, LocFlags: LocFlags{LocHeld, LocCarried, LocOnGrnd, LocInRoom}},
			ObjPrep:   "with",
			Obj2:      ObjProp{HasObj: true},
			Action:    vFill,
			PreAction: preFill,
		},
		{
			Verb:      "fill",
			Obj1:      ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgCont, LocFlags: LocFlags{LocHeld, LocCarried, LocOnGrnd, LocInRoom}},
			Action:    vFill,
			PreAction: preFill,
		},
		{
			Verb:   "find",
			Obj1:   ObjProp{HasObj: true},
			Action: vFind,
		},
		{
			Verb:   "follow",
			Action: vFollow,
		},
		{
			Verb:   "follow",
			Obj1:   ObjProp{HasObj: true},
			Action: vFollow,
		},
		{
			Verb:   "frobozz",
			Action: vFrobozz,
		},
		{
			Verb:      "give",
			Obj1:      ObjProp{HasObj: true, LocFlags: LocFlags{LocMany, LocHeld, LocHave}},
			ObjPrep:   "to",
			Obj2:      ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgPerson, LocFlags: LocFlags{LocOnGrnd}},
			Action:    vGive,
			PreAction: preGive,
		},
		{
			Verb:      "give",
			Obj1:      ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgPerson, LocFlags: LocFlags{LocOnGrnd}},
			Obj2:      ObjProp{HasObj: true, LocFlags: LocFlags{LocMany, LocHeld, LocHave}},
			Action:    vSGive,
			PreAction: preSGive,
			NormVerb:  "sgive",
		},
		{
			Verb:   "hatch",
			Obj1:   ObjProp{HasObj: true},
			Action: vHatch,
		},
		{
			Verb:   "hello",
			Action: vHello,
		},
		{
			Verb:   "hello",
			Obj1:   ObjProp{HasObj: true},
			Action: vHello,
		},
		{
			Verb:   "incant",
			Action: vIncant,
		},
		{
			Verb:    "inflate",
			Obj1:    ObjProp{HasObj: true},
			ObjPrep: "with",
			Obj2:    ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgTool, LocFlags: LocFlags{LocOnGrnd, LocInRoom, LocHeld, LocCarried}},
			Action:  vInflate,
		},
		{
			Verb:   "jump",
			Action: vLeap,
		},
		{
			Verb:     "jump",
			VrbPrep:  "over",
			Obj1:     ObjProp{HasObj: true},
			Action:   vLeap,
			NormVerb: "leap",
		},
		{
			Verb:     "jump",
			VrbPrep:  "across",
			Obj1:     ObjProp{HasObj: true},
			Action:   vLeap,
			NormVerb: "leap",
		},
		{
			Verb:     "jump",
			VrbPrep:  "in",
			Obj1:     ObjProp{HasObj: true},
			Action:   vLeap,
			NormVerb: "leap",
		},
		{
			Verb:     "jump",
			VrbPrep:  "from",
			Obj1:     ObjProp{HasObj: true},
			Action:   vLeap,
			NormVerb: "leap",
		},
		{
			Verb:     "jump",
			VrbPrep:  "off",
			Obj1:     ObjProp{HasObj: true},
			Action:   vLeap,
			NormVerb: "leap",
		},
		{
			Verb:   "kick",
			Obj1:   ObjProp{HasObj: true},
			Action: vKick,
		},
		{
			Verb:     "kill",
			Obj1:     ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgPerson, LocFlags: LocFlags{LocInRoom, LocOnGrnd}},
			ObjPrep:  "with",
			Obj2:     ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgWeapon, LocFlags: LocFlags{LocHeld, LocCarried, LocHave}},
			Action:   vAttack,
			NormVerb: "attack",
		},
		{
			Verb:   "stab",
			Obj1:   ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgPerson, LocFlags: LocFlags{LocInRoom, LocOnGrnd}},
			Action: vStab,
		},
		{
			Verb:     "stab",
			Obj1:     ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgPerson, LocFlags: LocFlags{LocInRoom, LocOnGrnd}},
			ObjPrep:  "with",
			Obj2:     ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgWeapon, LocFlags: LocFlags{LocHeld, LocCarried, LocHave}},
			Action:   vAttack,
			NormVerb: "attack",
		},
		{
			Verb:   "kiss",
			Obj1:   ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgPerson, LocFlags: LocFlags{LocOnGrnd, LocInRoom}},
			Action: vKiss,
		},
		{
			Verb:    "knock",
			VrbPrep: "at",
			Obj1:    ObjProp{HasObj: true},
			Action:  vKnock,
		},
		{
			Verb:    "knock",
			VrbPrep: "on",
			Obj1:    ObjProp{HasObj: true},
			Action:  vKnock,
		},
		{
			Verb:     "knock",
			VrbPrep:  "down",
			Obj1:     ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgPerson, LocFlags: LocFlags{LocInRoom, LocOnGrnd}},
			Action:   vAttack,
			NormVerb: "attack",
		},
		{
			Verb:   "launch",
			Obj1:   ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgVeh},
			Action: vLaunch,
		},
		{
			Verb:    "lean",
			VrbPrep: "on",
			Obj1:    ObjProp{HasObj: true, LocFlags: LocFlags{LocHeld, LocHave}},
			Action:  vLeanOn,
		},
		{
			Verb:   "leave",
			Action: vLeave,
		},
		{
			Verb:      "leave",
			Obj1:      ObjProp{HasObj: true},
			Action:    vDrop,
			PreAction: preDrop,
			NormVerb:  "drop",
		},
		{
			Verb:     "light",
			Obj1:     ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgLight, LocFlags: LocFlags{LocHeld, LocCarried, LocOnGrnd, LocInRoom, LocTake, LocHave}},
			Action:   vLampOn,
			NormVerb: "lamp on",
		},
		{
			Verb:      "light",
			Obj1:      ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgBurn, LocFlags: LocFlags{LocInRoom, LocOnGrnd, LocHeld, LocCarried}},
			ObjPrep:   "with",
			Obj2:      ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgFlame, LocFlags: LocFlags{LocHeld, LocCarried, LocHave, LocInRoom, LocOnGrnd}},
			Action:    vBurn,
			PreAction: preBurn,
			NormVerb:  "burn",
		},
		{
			Verb:     "listen",
			VrbPrep:  "to",
			Obj1:     ObjProp{HasObj: true},
			Action:   vListen,
			NormVerb: "listen",
		},
		{
			Verb:     "listen",
			VrbPrep:  "for",
			Obj1:     ObjProp{HasObj: true},
			Action:   vListen,
			NormVerb: "listen",
		},
		{
			Verb:    "lock",
			Obj1:    ObjProp{HasObj: true, LocFlags: LocFlags{LocInRoom, LocOnGrnd}},
			ObjPrep: "with",
			Obj2:    ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgTool, LocFlags: LocFlags{LocHeld, LocCarried, LocInRoom, LocOnGrnd, LocTake}},
			Action:  vLock,
		},
		{
			Verb:   "look",
			Action: vLook,
		},
		{
			Verb:     "look",
			VrbPrep:  "around",
			Obj1:     ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgKludge},
			Action:   vLook,
			NormVerb: "look",
		},
		{
			Verb:     "look",
			VrbPrep:  "up",
			Obj1:     ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgKludge},
			Action:   vLook,
			NormVerb: "look",
		},
		{
			Verb:     "look",
			VrbPrep:  "down",
			Obj1:     ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgKludge},
			Action:   vLook,
			NormVerb: "look",
		},
		{
			Verb:     "look",
			VrbPrep:  "at",
			Obj1:     ObjProp{HasObj: true, LocFlags: LocFlags{LocHeld, LocCarried, LocInRoom, LocOnGrnd, LocMany}},
			Action:   vExamine,
			NormVerb: "examine",
		},
		{
			Verb:     "look",
			VrbPrep:  "at",
			Obj1:     ObjProp{HasObj: true, LocFlags: LocFlags{LocHeld, LocCarried, LocInRoom, LocOnGrnd}},
			ObjPrep:  "with",
			Obj2:     ObjProp{HasObj: true},
			Action:   vRead,
			NormVerb: "read",
		},
		{
			Verb:     "look",
			VrbPrep:  "for",
			Obj1:     ObjProp{HasObj: true},
			Action:   vFind,
			NormVerb: "find",
		},
		{
			Verb:    "look",
			VrbPrep: "on",
			Obj1:    ObjProp{HasObj: true},
			Action:  vLookOn,
		},
		{
			Verb:     "look",
			VrbPrep:  "with",
			Obj1:     ObjProp{HasObj: true, LocFlags: LocFlags{LocHeld, LocCarried, LocInRoom, LocOnGrnd, LocMany}},
			Action:   vLookInside,
			NormVerb: "look inside",
		},
		{
			Verb:    "look",
			VrbPrep: "under",
			Obj1:    ObjProp{HasObj: true},
			Action:  vLookUnder,
		},
		{
			Verb:    "look",
			VrbPrep: "behind",
			Obj1:    ObjProp{HasObj: true},
			Action:  vLookBehind,
		},
		{
			Verb:     "look",
			VrbPrep:  "in",
			Obj1:     ObjProp{HasObj: true, LocFlags: LocFlags{LocHeld, LocCarried, LocInRoom, LocOnGrnd, LocMany}},
			Action:   vLookInside,
			NormVerb: "look inside",
		},
		{
			Verb:   "lower",
			Obj1:   ObjProp{HasObj: true},
			Action: vLower,
		},
		{
			Verb:    "lubricate",
			Obj1:    ObjProp{HasObj: true},
			ObjPrep: "with",
			Obj2:    ObjProp{HasObj: true, LocFlags: LocFlags{LocHeld, LocCarried}},
			Action:  vOil,
		},
		{
			Verb:   "make",
			Obj1:   ObjProp{HasObj: true},
			Action: vMake,
		},
		{
			Verb:    "melt",
			Obj1:    ObjProp{HasObj: true},
			ObjPrep: "with",
			Obj2:    ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgFlame, LocFlags: LocFlags{LocHeld, LocCarried, LocOnGrnd, LocInRoom}},
			Action:  vMelt,
		},
		{
			Verb:      "move",
			Obj1:      ObjProp{HasObj: true, LocFlags: LocFlags{LocOnGrnd, LocInRoom}},
			Action:    vMove,
			PreAction: preMove,
		},
		{
			Verb:     "move",
			Obj1:     ObjProp{HasObj: true, LocFlags: LocFlags{LocOnGrnd, LocInRoom}},
			Obj2:     ObjProp{HasObj: true},
			Action:   vPushTo,
			NormVerb: "push to",
		},
		{
			Verb:     "move",
			Obj1:     ObjProp{HasObj: true, LocFlags: LocFlags{LocOnGrnd, LocInRoom}},
			ObjPrep:  "to",
			Obj2:     ObjProp{HasObj: true},
			Action:   vPushTo,
			NormVerb: "push to",
		},
		{
			Verb:      "move",
			Obj1:      ObjProp{HasObj: true, LocFlags: LocFlags{LocHeld, LocMany, LocHave}},
			ObjPrep:   "in",
			Obj2:      ObjProp{HasObj: true},
			Action:    vPut,
			PreAction: prePut,
			NormVerb:  "put",
		},
		{
			Verb:      "move",
			Obj1:      ObjProp{HasObj: true},
			ObjPrep:   "with",
			Obj2:      ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgTool},
			Action:    vTurn,
			PreAction: preTurn,
			NormVerb:  "turn",
		},
		{
			Verb:      "roll",
			VrbPrep:   "up",
			Obj1:      ObjProp{HasObj: true, LocFlags: LocFlags{LocOnGrnd, LocInRoom}},
			Action:    vMove,
			PreAction: preMove,
			NormVerb:  "move",
		},
		{
			Verb:      "roll",
			Obj1:      ObjProp{HasObj: true, LocFlags: LocFlags{LocOnGrnd, LocInRoom}},
			Action:    vMove,
			PreAction: preMove,
			NormVerb:  "move",
		},
		{
			Verb:   "mumble",
			Action: vMumble,
		},
		{
			Verb:   "odysseus",
			Action: vOdysseus,
		},
		{
			Verb:   "open",
			Obj1:   ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgDoor, LocFlags: LocFlags{LocOnGrnd, LocInRoom, LocHeld, LocCarried}},
			Action: vOpen,
		},
		{
			Verb:     "open",
			VrbPrep:  "up",
			Obj1:     ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgDoor, LocFlags: LocFlags{LocOnGrnd, LocInRoom, LocHeld, LocCarried}},
			Action:   vOpen,
			NormVerb: "open",
		},
		{
			Verb:    "open",
			Obj1:    ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgDoor, LocFlags: LocFlags{LocOnGrnd, LocInRoom, LocHeld, LocCarried}},
			ObjPrep: "with",
			Obj2:    ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgTool, LocFlags: LocFlags{LocOnGrnd, LocInRoom, LocHeld, LocCarried, LocHave}},
			Action:  vOpen,
		},
		{
			Verb:   "pick",
			Obj1:   ObjProp{HasObj: true},
			Action: vPick,
		},
		{
			Verb:    "pick",
			Obj1:    ObjProp{HasObj: true},
			ObjPrep: "with",
			Obj2:    ObjProp{HasObj: true},
			Action:  vPick,
		},
		{
			Verb:      "pick",
			VrbPrep:   "up",
			Obj1:      ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgTake, LocFlags: LocFlags{LocOnGrnd, LocMany}},
			Action:    vTake,
			PreAction: preTake,
			NormVerb:  "take",
		},
		{
			Verb:   "play",
			Obj1:   ObjProp{HasObj: true},
			Action: vPlay,
		},
		{
			Verb:    "plug",
			Obj1:    ObjProp{HasObj: true},
			ObjPrep: "with",
			Obj2:    ObjProp{HasObj: true},
			Action:  vPlug,
		},
		{
			Verb:   "plugh",
			Action: vAdvent,
		},
		{
			Verb:      "poke",
			Obj1:      ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgPerson, LocFlags: LocFlags{LocOnGrnd, LocInRoom}},
			ObjPrep:   "with",
			Obj2:      ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgWeapon, LocFlags: LocFlags{LocHeld, LocCarried, LocHave}},
			Action:    vMung,
			PreAction: preMung,
			NormVerb:  "mung",
		},
		{
			Verb:      "puncture",
			Obj1:      ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgPerson, LocFlags: LocFlags{LocOnGrnd, LocInRoom}},
			ObjPrep:   "with",
			Obj2:      ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgWeapon, LocFlags: LocFlags{LocHeld, LocCarried, LocHave}},
			Action:    vMung,
			PreAction: preMung,
			NormVerb:  "mung",
		},
		{
			Verb:      "pour",
			Obj1:      ObjProp{HasObj: true, LocFlags: LocFlags{LocHeld, LocCarried}},
			Action:    vDrop,
			PreAction: preDrop,
			NormVerb:  "drop",
		},
		{
			Verb:      "pour",
			Obj1:      ObjProp{HasObj: true, LocFlags: LocFlags{LocHeld, LocCarried}},
			ObjPrep:   "in",
			Obj2:      ObjProp{HasObj: true},
			Action:    vDrop,
			PreAction: preDrop,
			NormVerb:  "drop",
		},
		{
			Verb:     "pour",
			Obj1:     ObjProp{HasObj: true, LocFlags: LocFlags{LocHeld, LocCarried}},
			ObjPrep:  "on",
			Obj2:     ObjProp{HasObj: true},
			Action:   vPourOn,
			NormVerb: "pour on",
		},
		{
			Verb:      "pour",
			Obj1:      ObjProp{HasObj: true, LocFlags: LocFlags{LocHeld, LocCarried}},
			ObjPrep:   "from",
			Obj2:      ObjProp{HasObj: true},
			Action:    vDrop,
			PreAction: preDrop,
			NormVerb:  "drop",
		},
		{
			Verb:   "pray",
			Action: vPray,
		},
		{
			Verb:      "pull",
			Obj1:      ObjProp{HasObj: true, LocFlags: LocFlags{LocOnGrnd, LocInRoom}},
			Action:    vMove,
			PreAction: preMove,
			NormVerb:  "move",
		},
		{
			Verb:      "pull",
			VrbPrep:   "on",
			Obj1:      ObjProp{HasObj: true, LocFlags: LocFlags{LocOnGrnd, LocInRoom}},
			Action:    vMove,
			PreAction: preMove,
			NormVerb:  "move",
		},
		{
			Verb:      "pull",
			VrbPrep:   "up",
			Obj1:      ObjProp{HasObj: true, LocFlags: LocFlags{LocOnGrnd, LocInRoom}},
			Action:    vMove,
			PreAction: preMove,
			NormVerb:  "move",
		},
		{
			Verb:     "pump",
			VrbPrep:  "up",
			Obj1:     ObjProp{HasObj: true},
			Action:   vPump,
			NormVerb: "pump",
		},
		{
			Verb:     "pump",
			VrbPrep:  "up",
			Obj1:     ObjProp{HasObj: true},
			ObjPrep:  "with",
			Obj2:     ObjProp{HasObj: true},
			Action:   vPump,
			NormVerb: "pump",
		},
		{
			Verb:     "push",
			Obj1:     ObjProp{HasObj: true, LocFlags: LocFlags{LocInRoom, LocOnGrnd}},
			Obj2:     ObjProp{HasObj: true},
			Action:   vPushTo,
			NormVerb: "push to",
		},
		{
			Verb:     "push",
			Obj1:     ObjProp{HasObj: true, LocFlags: LocFlags{LocInRoom, LocOnGrnd}},
			ObjPrep:  "to",
			Obj2:     ObjProp{HasObj: true},
			Action:   vPushTo,
			NormVerb: "push to",
		},
		{
			Verb:   "push",
			Obj1:   ObjProp{HasObj: true, LocFlags: LocFlags{LocInRoom, LocOnGrnd, LocMany}},
			Action: vPush,
		},
		{
			Verb:     "push",
			VrbPrep:  "on",
			Obj1:     ObjProp{HasObj: true, LocFlags: LocFlags{LocInRoom, LocOnGrnd}},
			Action:   vPush,
			NormVerb: "push",
		},
		{
			Verb:      "push",
			Obj1:      ObjProp{HasObj: true},
			ObjPrep:   "with",
			Obj2:      ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgTool},
			Action:    vTurn,
			NormVerb:  "turn",
			PreAction: preTurn,
		},
		{
			Verb:     "push",
			Obj1:     ObjProp{HasObj: true},
			ObjPrep:  "under",
			Obj2:     ObjProp{HasObj: true},
			Action:   vPutUnder,
			NormVerb: "put under",
		},
		{
			Verb:      "put",
			Obj1:      ObjProp{HasObj: true, LocFlags: LocFlags{LocHeld, LocMany, LocHave}},
			ObjPrep:   "in",
			Obj2:      ObjProp{HasObj: true},
			Action:    vPut,
			PreAction: prePut,
		},
		{
			Verb:      "put",
			Obj1:      ObjProp{HasObj: true, LocFlags: LocFlags{LocHeld, LocMany, LocHave}},
			ObjPrep:   "on",
			Obj2:      ObjProp{HasObj: true},
			Action:    vPutOn,
			PreAction: prePut,
			NormVerb:  "put on",
		},
		{
			Verb:      "put",
			VrbPrep:   "down",
			Obj1:      ObjProp{HasObj: true, LocFlags: LocFlags{LocHeld, LocMany}},
			Action:    vDrop,
			PreAction: preDrop,
			NormVerb:  "drop",
		},
		{
			Verb:     "put",
			Obj1:     ObjProp{HasObj: true, LocFlags: LocFlags{LocHeld, LocHave}},
			ObjPrep:  "under",
			Obj2:     ObjProp{HasObj: true},
			Action:   vPutUnder,
			NormVerb: "put under",
		},
		{
			Verb:     "put",
			VrbPrep:  "out",
			Obj1:     ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgOn, LocFlags: LocFlags{LocHeld, LocCarried, LocOnGrnd, LocInRoom, LocTake, LocHave}},
			Action:   vLampOff,
			NormVerb: "lamp off",
		},
		{
			Verb:     "put",
			VrbPrep:  "on",
			Obj1:     ObjProp{HasObj: true, LocFlags: LocFlags{LocInRoom, LocOnGrnd, LocCarried, LocMany}},
			Action:   vWear,
			NormVerb: "wear",
		},
		{
			Verb:     "put",
			Obj1:     ObjProp{HasObj: true, LocFlags: LocFlags{LocHeld, LocMany, LocHave}},
			ObjPrep:  "behind",
			Obj2:     ObjProp{HasObj: true},
			Action:   vPutBehind,
			NormVerb: "put behind",
		},
		{
			Verb:   "raise",
			Obj1:   ObjProp{HasObj: true},
			Action: vRaise,
		},
		{
			Verb:     "raise",
			VrbPrep:  "up",
			Obj1:     ObjProp{HasObj: true},
			Action:   vRaise,
			NormVerb: "raise",
		},
		{
			Verb:   "rape",
			Obj1:   ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgPerson},
			Action: vRape,
		},
		{
			Verb:      "read",
			Obj1:      ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgRead, LocFlags: LocFlags{LocHeld, LocCarried, LocOnGrnd, LocInRoom, LocTake}},
			Action:    vRead,
			PreAction: preRead,
		},
		{
			Verb:      "read",
			VrbPrep:   "from",
			Obj1:      ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgRead, LocFlags: LocFlags{LocHeld, LocCarried, LocOnGrnd, LocInRoom, LocTake}},
			Action:    vRead,
			PreAction: preRead,
			NormVerb:  "read",
		},
		{
			Verb:      "read",
			Obj1:      ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgRead, LocFlags: LocFlags{LocHeld, LocCarried, LocOnGrnd, LocInRoom, LocTake}},
			ObjPrep:   "with",
			Obj2:      ObjProp{HasObj: true},
			Action:    vRead,
			PreAction: preRead,
			NormVerb:  "read",
		},
		{
			Verb:     "read",
			Obj1:     ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgRead, LocFlags: LocFlags{LocHeld, LocCarried, LocOnGrnd, LocInRoom, LocTake}},
			Obj2:     ObjProp{HasObj: true},
			Action:   vReadPage,
			NormVerb: "read page",
		},
		{
			Verb:   "repent",
			Action: vRepent,
		},
		{
			Verb:   "ring",
			Obj1:   ObjProp{HasObj: true, LocFlags: LocFlags{LocTake}},
			Action: vRing,
		},
		{
			Verb:    "ring",
			Obj1:    ObjProp{HasObj: true, LocFlags: LocFlags{LocTake}},
			ObjPrep: "with",
			Obj2:    ObjProp{HasObj: true},
			Action:  vRing,
		},
		{
			Verb:   "rub",
			Obj1:   ObjProp{HasObj: true},
			Action: vRub,
		},
		{
			Verb:    "rub",
			Obj1:    ObjProp{HasObj: true},
			ObjPrep: "with",
			Obj2:    ObjProp{HasObj: true},
			Action:  vRub,
		},
		{
			Verb:     "talk",
			VrbPrep:  "to",
			Obj1:     ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgPerson, LocFlags: LocFlags{LocInRoom}},
			Action:   vTell,
			NormVerb: "tell",
		},
		{
			Verb:   "say",
			Action: vSay,
		},
		{
			Verb:   "search",
			Obj1:   ObjProp{HasObj: true},
			Action: vSearch,
		},
		{
			Verb:     "search",
			VrbPrep:  "in",
			Obj1:     ObjProp{HasObj: true},
			Action:   vSearch,
			NormVerb: "search",
		},
		{
			Verb:     "search",
			VrbPrep:  "for",
			Obj1:     ObjProp{HasObj: true},
			Action:   vFind,
			NormVerb: "find",
		},
		{
			Verb:     "send",
			VrbPrep:  "for",
			Obj1:     ObjProp{HasObj: true},
			Action:   vSend,
			NormVerb: "send",
		},
		{
			Verb:   "shake",
			Obj1:   ObjProp{HasObj: true, LocFlags: LocFlags{LocHave}},
			Action: vShake,
		},
		{
			Verb:   "skip",
			Action: vSkip,
		},
		{
			Verb:     "slide",
			Obj1:     ObjProp{HasObj: true},
			ObjPrep:  "under",
			Obj2:     ObjProp{HasObj: true},
			Action:   vPutUnder,
			NormVerb: "put under",
		},
		{
			Verb:     "slide",
			Obj1:     ObjProp{HasObj: true, LocFlags: LocFlags{LocInRoom, LocOnGrnd}},
			Obj2:     ObjProp{HasObj: true},
			Action:   vPushTo,
			NormVerb: "push to",
		},
		{
			Verb:     "slide",
			Obj1:     ObjProp{HasObj: true, LocFlags: LocFlags{LocInRoom, LocOnGrnd}},
			ObjPrep:  "to",
			Obj2:     ObjProp{HasObj: true},
			Action:   vPushTo,
			NormVerb: "push to",
		},
		{
			Verb:   "smell",
			Obj1:   ObjProp{HasObj: true},
			Action: vSmell,
		},
		{
			Verb:   "spin",
			Obj1:   ObjProp{HasObj: true},
			Action: vSpin,
		},
		{
			Verb:    "spray",
			Obj1:    ObjProp{HasObj: true},
			ObjPrep: "on",
			Obj2:    ObjProp{HasObj: true},
			Action:  vSpray,
		},
		{
			Verb:    "spray",
			Obj1:    ObjProp{HasObj: true},
			ObjPrep: "with",
			Obj2:    ObjProp{HasObj: true},
			Action:  vSSpray,
		},
		{
			Verb:   "squeeze",
			Obj1:   ObjProp{HasObj: true},
			Action: vSqueeze,
		},
		{
			Verb:      "squeeze",
			Obj1:      ObjProp{HasObj: true},
			ObjPrep:   "on",
			Obj2:      ObjProp{HasObj: true},
			Action:    vPut,
			PreAction: prePut,
			NormVerb:  "put",
		},
		{
			Verb:   "stand",
			Action: vStand,
		},
		{
			Verb:     "stand",
			VrbPrep:  "up",
			Obj1:     ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgKludge},
			Action:   vStand,
			NormVerb: "stand",
		},
		{
			Verb:   "stay",
			Action: vStay,
		},
		{
			Verb:     "strike",
			Obj1:     ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgPerson, LocFlags: LocFlags{LocInRoom, LocOnGrnd}},
			ObjPrep:  "with",
			Obj2:     ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgWeapon, LocFlags: LocFlags{LocHeld, LocCarried, LocHave, LocInRoom, LocOnGrnd}},
			Action:   vAttack,
			NormVerb: "attack",
		},
		{
			Verb:   "strike",
			Obj1:   ObjProp{HasObj: true, LocFlags: LocFlags{LocInRoom, LocOnGrnd, LocHeld, LocCarried}},
			Action: vStrike,
		},
		{
			Verb:   "swim",
			Action: vSwim,
		},
		{
			Verb:     "swim",
			VrbPrep:  "in",
			Obj1:     ObjProp{HasObj: true},
			Action:   vSwim,
			NormVerb: "swim",
		},
		{
			Verb:     "swim",
			VrbPrep:  "across",
			Obj1:     ObjProp{HasObj: true},
			Action:   vSwim,
			NormVerb: "swim",
		},
		{
			Verb:   "swing",
			Obj1:   ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgWeapon, LocFlags: LocFlags{LocHeld, LocCarried, LocHave}},
			Action: vSwing,
		},
		{
			Verb:    "swing",
			Obj1:    ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgWeapon, LocFlags: LocFlags{LocHeld, LocCarried, LocHave}},
			ObjPrep: "at",
			Obj2:    ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgPerson, LocFlags: LocFlags{LocOnGrnd, LocInRoom}},
			Action:  vSwing,
		},
		{
			Verb:      "take",
			Obj1:      ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgTake, LocFlags: LocFlags{LocOnGrnd, LocInRoom, LocMany}},
			Action:    vTake,
			PreAction: preTake,
		},
		{
			Verb:      "take",
			VrbPrep:   "in",
			Obj1:      ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgVeh, LocFlags: LocFlags{LocOnGrnd, LocInRoom}},
			Action:    vBoard,
			PreAction: preBoard,
			NormVerb:  "board",
		},
		{
			Verb:     "take",
			VrbPrep:  "out",
			Obj1:     ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgKludge, LocFlags: LocFlags{LocOnGrnd, LocInRoom}},
			Action:   vDisembark,
			NormVerb: "disembark",
		},
		{
			Verb:     "take",
			VrbPrep:  "on",
			Obj1:     ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgVeh, LocFlags: LocFlags{LocOnGrnd, LocInRoom}},
			Action:   vClimbOn,
			NormVerb: "climb on",
		},
		{
			Verb:     "take",
			VrbPrep:  "up",
			Obj1:     ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgKludge},
			Action:   vStand,
			NormVerb: "stand",
		},
		{
			Verb:      "take",
			Obj1:      ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgTake, LocFlags: LocFlags{LocCarried, LocInRoom, LocMany}},
			ObjPrep:   "out",
			Obj2:      ObjProp{HasObj: true},
			Action:    vTake,
			PreAction: preTake,
		},
		{
			Verb:      "take",
			Obj1:      ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgTake, LocFlags: LocFlags{LocCarried, LocInRoom, LocMany}},
			ObjPrep:   "off",
			Obj2:      ObjProp{HasObj: true},
			Action:    vTake,
			PreAction: preTake,
		},
		{
			Verb:      "take",
			Obj1:      ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgTake, LocFlags: LocFlags{LocCarried, LocInRoom, LocMany}},
			ObjPrep:   "from",
			Obj2:      ObjProp{HasObj: true},
			Action:    vTake,
			PreAction: preTake,
		},
		{
			Verb:   "tell",
			Obj1:   ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgPerson, LocFlags: LocFlags{LocInRoom}},
			Action: vTell,
		},
		{
			Verb:    "tell",
			Obj1:    ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgPerson, LocFlags: LocFlags{LocInRoom}},
			ObjPrep: "about",
			Obj2:    ObjProp{HasObj: true},
			Action:  vTell,
		},
		{
			Verb:    "throw",
			Obj1:    ObjProp{HasObj: true, LocFlags: LocFlags{LocHeld, LocCarried, LocHave}},
			ObjPrep: "at",
			Obj2:    ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgPerson, LocFlags: LocFlags{LocOnGrnd, LocInRoom}},
			Action:  vThrow,
		},
		{
			Verb:    "throw",
			Obj1:    ObjProp{HasObj: true, LocFlags: LocFlags{LocHeld, LocCarried, LocHave}},
			ObjPrep: "with",
			Obj2:    ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgPerson, LocFlags: LocFlags{LocOnGrnd, LocInRoom}},
			Action:  vThrow,
		},
		{
			Verb:   "throw",
			Obj1:   ObjProp{HasObj: true},
			Obj2:   ObjProp{HasObj: true},
			Action: vOverboard,
		},
		{
			Verb:      "throw",
			Obj1:      ObjProp{HasObj: true, LocFlags: LocFlags{LocHeld, LocCarried, LocHave}},
			ObjPrep:   "in",
			Obj2:      ObjProp{HasObj: true},
			Action:    vPut,
			PreAction: prePut,
			NormVerb:  "put",
		},
		{
			Verb:      "throw",
			Obj1:      ObjProp{HasObj: true, LocFlags: LocFlags{LocHeld, LocCarried, LocHave}},
			ObjPrep:   "on",
			Obj2:      ObjProp{HasObj: true},
			Action:    vPutOn,
			PreAction: prePut,
			NormVerb:  "put on",
		},
		{
			Verb:     "throw",
			Obj1:     ObjProp{HasObj: true, LocFlags: LocFlags{LocHeld, LocCarried, LocHave}},
			ObjPrep:  "off",
			Obj2:     ObjProp{HasObj: true},
			Action:   vThrowOff,
			NormVerb: "throw off",
		},
		{
			Verb:     "throw",
			Obj1:     ObjProp{HasObj: true, LocFlags: LocFlags{LocHeld, LocCarried, LocHave}},
			ObjPrep:  "over",
			Obj2:     ObjProp{HasObj: true},
			Action:   vThrowOff,
			NormVerb: "throw off",
		},
		{
			Verb:    "tie",
			Obj1:    ObjProp{HasObj: true},
			ObjPrep: "to",
			Obj2:    ObjProp{HasObj: true},
			Action:  vTie,
		},
		{
			Verb:    "tie",
			VrbPrep: "up",
			Obj1:    ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgPerson, LocFlags: LocFlags{LocOnGrnd, LocInRoom}},
			ObjPrep: "with",
			Obj2:    ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgTool, LocFlags: LocFlags{LocOnGrnd, LocInRoom, LocHeld, LocCarried, LocHave}},
			Action:  vTieUp,
		},
		{
			Verb:   "treasure",
			Action: vTreasure,
		},
		{
			Verb:      "turn",
			Obj1:      ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgTurn, LocFlags: LocFlags{LocHeld, LocCarried, LocOnGrnd, LocInRoom}},
			ObjPrep:   "with",
			Obj2:      ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgKludge},
			Action:    vTurn,
			PreAction: preTurn,
		},
		{
			Verb:     "turn",
			VrbPrep:  "on",
			Obj1:     ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgLight, LocFlags: LocFlags{LocHeld, LocCarried, LocOnGrnd, LocInRoom}},
			Action:   vLampOn,
			NormVerb: "lamp on",
		},
		{
			Verb:     "turn",
			VrbPrep:  "on",
			Obj1:     ObjProp{HasObj: true},
			ObjPrep:  "with",
			Obj2:     ObjProp{HasObj: true, LocFlags: LocFlags{LocHave}},
			Action:   vLampOn,
			NormVerb: "lamp on",
		},
		{
			Verb:     "turn",
			VrbPrep:  "off",
			Obj1:     ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgOn, LocFlags: LocFlags{LocHeld, LocCarried, LocOnGrnd, LocInRoom, LocTake, LocHave}},
			Action:   vLampOff,
			NormVerb: "lamp off",
		},
		{
			Verb:      "turn",
			Obj1:      ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgTurn},
			ObjPrep:   "to",
			Obj2:      ObjProp{HasObj: true},
			Action:    vTurn,
			PreAction: preTurn,
		},
		{
			Verb:      "turn",
			Obj1:      ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgTurn},
			ObjPrep:   "for",
			Obj2:      ObjProp{HasObj: true},
			Action:    vTurn,
			PreAction: preTurn,
		},
		{
			Verb:    "unlock",
			Obj1:    ObjProp{HasObj: true, LocFlags: LocFlags{LocOnGrnd, LocInRoom}},
			ObjPrep: "with",
			Obj2:    ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgTool, LocFlags: LocFlags{LocHeld, LocCarried, LocOnGrnd, LocInRoom, LocTake}},
			Action:  vUnlock,
		},
		{
			Verb:    "untie",
			Obj1:    ObjProp{HasObj: true, LocFlags: LocFlags{LocOnGrnd, LocInRoom, LocHeld, LocCarried}},
			ObjPrep: "from",
			Obj2:    ObjProp{HasObj: true},
			Action:  vUntie,
		},
		{
			Verb:   "untie",
			Obj1:   ObjProp{HasObj: true, LocFlags: LocFlags{LocOnGrnd, LocInRoom, LocHeld, LocCarried}},
			Action: vUntie,
		},
		{
			Verb:   "wait",
			Action: vWait,
		},
		{
			Verb:     "wake",
			Obj1:     ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgPerson, LocFlags: LocFlags{LocOnGrnd, LocInRoom}},
			Action:   vAlarm,
			NormVerb: "alarm",
		},
		{
			Verb:     "wake",
			VrbPrep:  "up",
			Obj1:     ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgPerson, LocFlags: LocFlags{LocOnGrnd, LocInRoom}},
			Action:   vAlarm,
			NormVerb: "alarm",
		},
		{
			Verb:     "walk",
			Action:   vWalkAround,
			NormVerb: "walk around",
		},
		{
			Verb:   "walk",
			Obj1:   ObjProp{HasObj: true},
			Action: vWalk,
		},
		{
			Verb:     "walk",
			VrbPrep:  "away",
			Obj1:     ObjProp{HasObj: true},
			Action:   vWalk,
			NormVerb: "walk",
		},
		{
			Verb:     "walk",
			VrbPrep:  "in",
			Obj1:     ObjProp{HasObj: true},
			Action:   vThrough,
			NormVerb: "through",
		},
		{
			Verb:     "walk",
			VrbPrep:  "with",
			Obj1:     ObjProp{HasObj: true},
			Action:   vThrough,
			NormVerb: "through",
		},
		{
			Verb:     "walk",
			VrbPrep:  "on",
			Obj1:     ObjProp{HasObj: true},
			Action:   vThrough,
			NormVerb: "through",
		},
		{
			Verb:     "walk",
			VrbPrep:  "over",
			Obj1:     ObjProp{HasObj: true},
			Action:   vLeap,
			NormVerb: "leap",
		},
		{
			Verb:    "walk",
			VrbPrep: "to",
			Obj1:    ObjProp{HasObj: true},
			Action:  vWalkTo,
		},
		{
			Verb:    "walk",
			VrbPrep: "around",
			Obj1:    ObjProp{HasObj: true},
			Action:  vWalkAround,
		},
		{
			Verb:     "walk",
			VrbPrep:  "up",
			Obj1:     ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgClimb, LocFlags: LocFlags{LocOnGrnd, LocInRoom}},
			Action:   vClimbUp,
			NormVerb: "climb up",
		},
		{
			Verb:     "walk",
			VrbPrep:  "down",
			Obj1:     ObjProp{HasObj: true, ObjFlags: FlgSearch | FlgClimb, LocFlags: LocFlags{LocOnGrnd, LocInRoom}},
			Action:   vClimbDown,
			NormVerb: "climb down",
		},
		{
			Verb:   "wave",
			Obj1:   ObjProp{HasObj: true, LocFlags: LocFlags{LocHeld, LocCarried, LocTake, LocHave}},
			Action: vWave,
		},
		{
			Verb:    "wave",
			Obj1:    ObjProp{HasObj: true, LocFlags: LocFlags{LocHeld, LocCarried, LocTake, LocHave}},
			ObjPrep: "at",
			Obj2:    ObjProp{HasObj: true},
			Action:  vWave,
		},
		{
			Verb:     "wave",
			VrbPrep:  "at",
			Obj1:     ObjProp{HasObj: true},
			Action:   vWave,
			NormVerb: "wave",
		},
		{
			Verb:   "wear",
			Obj1:   ObjProp{HasObj: true},
			Action: vWear,
		},
		{
			Verb:   "win",
			Action: vWin,
		},
		{
			Verb:   "wind",
			Obj1:   ObjProp{HasObj: true},
			Action: vWind,
		},
		{
			Verb:     "wind",
			VrbPrep:  "up",
			Obj1:     ObjProp{HasObj: true},
			Action:   vWind,
			NormVerb: "wind",
		},
		{
			Verb:   "wish",
			Action: vWish,
		},
		{
			Verb:   "yell",
			Action: vYell,
		},
		{
			Verb:   "zork",
			Action: vZork,
		},
	}
)
